# Generated by Django 3.1.2 on 2020-10-28 01:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('air', 'Air'), ('water', 'Water'), ('food', 'Food'), ('housing', 'Housing'), ('health', 'Health'), ('education', 'Education'), ('transportation', 'Transportation'), ('sexuality', 'Sexuality')], default='air', max_length=20)),
                ('slug', models.SlugField(max_length=25)),
                ('topic_image', models.ImageField(blank=True, null=True, upload_to='uploads/topics')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('article-reviews', 'Article Reviews'), ('book-reviews', 'Book Reviews'), ('commentaries', 'Commentaries')], db_index=True, default='article-choices', max_length=25)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('author', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/posts/images')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/posts/thumbnails')),
                ('imageurl', models.URLField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('review_item', models.TextField(blank=True, null=True)),
                ('topics', models.ManyToManyField(to='posts.Topic')),
            ],
            options={
                'ordering': ['posted_date', 'category', 'author'],
            },
        ),
    ]
