# Generated by Django 3.1.2 on 2020-10-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201008_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
